### ISSUE TITLE
ES6 export

### ISSUE THREAD

**Issue by ArianeNubee** [freaksauce/parentsUntil#2]
It would be very nice if you could make the module more easily compatible with ES6 imports. In theory it would be as simple as adding "export default parentsUntil", or something to that effect. Then it would be possible to simply "import parentsUntil from 'my/folder/file.js'" and it would work.

I wanted to use this in my project and ended up having to copy-paste the code into my helper functions because the import wouldn't work properly.

**Comment by freaksauce** [comment]
You could use require instead of import as this is written as an es5 module

**Comment by ArianeNubee** [comment]
Sadly, my bundler can only do one or the other. Require is an undefined function, it says.

**Comment by freaksauce** [comment]
@ArianeNubee I'm actually using this package in a project and I just use import with no problem. `import parentsUntil from 'parentsuntil'`. This is in a CRA App.

**Comment by ArianeNubee** [comment]
Ah, I apologize. My bundler requires me to put the whole path to the JS file or it won't import. The problem was never with your module.
